# Generated by Django 4.2.4 on 2023-10-29 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recruitments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_personal', models.EmailField(max_length=254)),
                ('email_kiet', models.EmailField(max_length=254)),
                ('library_id', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
                ('day_scholar_hosteller', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=15)),
                ('payment_mode', models.CharField(max_length=15)),
                ('desk', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
