# Generated by Django 4.2.4 on 2023-10-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment23', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitments',
            name='recruitment_mail',
            field=models.BooleanField(default=False),
        ),
    ]
