# Generated by Django 4.2.4 on 2023-11-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment23', '0002_recruitments_recruitment_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitments',
            name='slot_mail',
            field=models.BooleanField(default=False),
        ),
    ]
