# Generated by Django 4.2.4 on 2023-11-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment23', '0003_recruitments_slot_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitments',
            name='slot_mail',
        ),
    ]
