# Generated by Django 4.2.4 on 2023-11-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment23', '0004_remove_recruitments_slot_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitments',
            name='interview_mail',
            field=models.BooleanField(default=False),
        ),
    ]
