# Generated by Django 4.2.4 on 2024-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment23', '0004_remove_recruitments_slot_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitments',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
