# Generated by Django 4.2.2 on 2023-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('shortDesc', models.TextField()),
                ('message', models.TextField()),
                ('url', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
