# Generated by Django 4.2.4 on 2023-09-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventman', '0002_formsubmission_end_date_formsubmission_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='about',
            field=models.TextField(default='https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/mobile_banner/62586fbf1a189_copy_of_d2c_banner__700__400px_.png'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='crousel',
            field=models.TextField(default='https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/mobile_banner/62586fbf1a189_copy_of_d2c_banner__700__400px_.png'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='sponsors',
            field=models.TextField(default='https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/mobile_banner/62586fbf1a189_copy_of_d2c_banner__700__400px_.png'),
            preserve_default=False,
        ),
    ]
