# Generated by Django 4.2.4 on 2023-09-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventman', '0003_formsubmission_about_formsubmission_crousel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='crousel',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='sponsors',
            field=models.TextField(default=''),
        ),
    ]
