# Generated by Django 4.2.4 on 2024-05-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventman', '0004_alter_formsubmission_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='is_coordinator',
            field=models.BooleanField(default=False, verbose_name='is coordinator'),
        ),
    ]
