# Generated by Django 4.2.2 on 2023-06-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventman', '0005_rename_page_url_formsubmission_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
            ],
        ),
    ]
