# Generated by Django 4.2.2 on 2023-07-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='events_created',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='events_participated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
