# Generated by Django 4.2.4 on 2023-10-28 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment2023', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitments',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
